server {

  location /featureserver/ {
    proxy_pass http://pg-feat-archeshedescriptors:9000/;
  }

  location /tileserver/ {
    proxy_pass http://pg-tile-archeshedescriptors:7800/tileserver/;
  }

  location / {
    proxy_pass http://archeshedescriptors:8000/;
  }

}